FROM alpine:edge

RUN apk add --no-cache \
    bash \
    curl \
    jq \
    git \
    build-base \
    python3 \
    cmake \
    clang \
    clang-extra-tools \
    boost-dev \
    boost-chrono \
    boost-filesystem \
    boost-system \
    boost-date_time \
    boost-unit_test_framework \ 
    suitesparse-dev \
    wget \
    zeromq-dev

LABEL maintainer="helicsdevelopers@helics.org"
LABEL date="2025-02-24"