FROM alpine:edge

RUN apk add --no-cache \
    bash \
    curl \
    jq \
    git \
    build-base \
    python3 \
    cmake \
    clang \
    clang-extra-tools \
    boost-dev \
    suitesparse-dev \
    wget \
    zeromq-dev

LABEL maintainer="helicsdevelopers@helics.org"
LABEL date="2026-04-24"